### ISSUE TITLE
It is not mobile and tablet responsive

### ISSUE THREAD

**Issue by VinayChaurasiya96** [daniel-jebarson/daniel-jebarson.github.io#4]
![Screenshot (85)](https://github.com/daniel-jebarson/daniel-jebarson.github.io/assets/80849410/269ea8fd-cfc8-4e90-a9ca-894b36dd0011)

**Comment by daniel-jebarson** [comment]
For now i had only done for pc. I had yet to do for mobile and tablet sizes

**Comment by daniel-jebarson** [comment]
This issue has been fixed now
